#### Problem Statement-1

Create the model which predicts house price based of House Area, No of Bedrooms and age of the house.


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math

In [2]:
#Read the dataset
df=pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

So here the indipendent variables are 3 so the Linear equation looks like
#### y=m1*x1+m2*x2+m3*x3+C

In [3]:
# In the data you can see beadroom column has Null value we need to replace with Median or
#you can use mean of that column
df.bedrooms.median()
df['bedrooms'] = df['bedrooms'].fillna(df.bedrooms.mean())


In [4]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg=linear_model.LinearRegression()# Creating object class for training a model
reg.fit(df[['area','bedrooms','age']],df['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
reg.predict([[3000,4,40]])

array([509589.63050731])

In [7]:
reg.coef_## Values for m1,m2,m3

array([  116.66950551, 18756.28806982, -3675.75111708])

In [8]:
reg.intercept_# Value of C

231586.00639409176

#### Problem Statement-2
Predict the salary of an employee based on years of experience, written test score and interview score

In [9]:
#Lets import the dataset
df2=pd.read_csv('hiring.csv')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Lets assume in exp column where Nan values are available these are the guys with 0 year experience
Lets replace these values with 0


In [10]:
df2['experience'] = df2['experience'].fillna(value='zero')

In [11]:
df2 # we can see that Exp column has experience in words lets convert that to number

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
# we can see that Exp column has experience in words lets convert that to number
!pip install word2number
from word2number import w2n

In [13]:
df2['experience']= df2['experience'].apply(w2n.word_to_num)

In [14]:
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [15]:
import math
mean_test_score = math.floor(df2['test_score(out of 10)'].mean())
mean_test_score

7

In [16]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(7)
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [17]:
reg=linear_model.LinearRegression()
reg.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']],df2['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [19]:
reg.predict([[12,10,10]])

array([93747.79628651])